### ISSUE TITLE
Add single-data port support

### ISSUE THREAD

**Issue by agoston** [bolcom/libunftp#121]
While deploying to kubernetes, we realized we don't actually need so many ports open in kubernetes if we use a single data port only.

(details: https://serverfault.com/questions/270745/why-does-ftp-passive-mode-require-a-port-range-as-opposed-to-only-one-port)

The upside of using a single port for control channel and another single port for data are many:
- kubernetes has no support for port ranges, which makes opening up thousands of ports a very remote possibility only;
- opening up a lot of ports is always seen as an impact on management, configuration and security in general;
- by identifying clients on the data port based on the control port's IP, we get added security against hijack attacks.

There are also downsides:
- There could be weird use cases where the data port is opened from another IP than the control port. This is normally reserved for advanced FTP usage that is not at all common these days.

- If a client connects multiple times from the same IP, and they both initiate data transfer, we can't identify which data port connection belongs to which client. A possible workaround would be

**Comment by wgfm** [comment]
We can already call `passive_ports` on a `Server` object with a port range. If we call that like `passive_ports(2121..=2121)`, it should start a server with only one data port. Granted, it's not a contender for a beauty pageant, but it should work.

**Comment by robklg** [comment]
Single data port is not impossible with regular FTP.

As clients can be behind NAT'ed source IPs, there is no guarantee that the data channel connection originates from the same client as the control connection where the transfer was initiated. It would also be a huge security hole.

A single port FTP would still however be possible to implement for a TLS-only mode server, using [session sharing](https://github.com/bolcom/libunftp/issues/320). The information (such as session ID) in the TLS handshake securely identifies the client.

As for the Kubernetes limitations. It is possible to use the proxy protocol, then only 1 single port is needed where all control and data connections are multiplexed through. However that still needs a larger port range on the outside / proxy server.
