### ISSUE TITLE
Support FileZilla with the Google Cloud Storage backend

### ISSUE THREAD

**Issue by Nonius** [bolcom/libunftp#143]
Since the Google Cloud Storage backend doesn't support directory times, the output of a `LIST` is like this:
```drwxr-xr-x            0            0              0            - /
drwxr-xr-x            0            0              0            - mydirectory
drwxr-xr-x            0            0              0            - test
drwxr-xr-x            0            0              0 Dec 13 14:52 /
-rwxr-xr-x            0            0             24 Jun 07 13:05 test_thingy
-rwxr-xr-x            0            0             21 Jun 07 13:06 thingy
```
FileZilla thinks that the directories are `- /`, `- mydirectory`, `- test` instead of `/`, `mydirectory`, `test`

**Comment by marksmithson** [comment]
Could this use the most recent time of a file within a directory?

I guess still need to handle an empty directory (assuming GCS supports that). Also could get quite expensive if looking for the most recent file recursively.

**Comment by hannesdejager** [comment]
@marksmithson what do you mean by:

>  Also could get quite expensive if looking for the most recent file recursively.

why would this be done recursively?

**Comment by robklg** [comment]
@hannesdejager I think what Mark means is, if you have something like `firstlevel/secondlevel/file`, where `firstlevel` is otherwise devoid of files, you would need to find something like the latest file. Although not sure how that would work, as the object store is not hierarchical. Something to investigate.

**Comment by hannesdejager** [comment]
Fixed by this: https://github.com/bolcom/libunftp/pull/415
