### ISSUE TITLE
Make local testing of the Google Cloud Storage backend possible

### ISSUE THREAD

**Issue by Nonius** [bolcom/libunftp#171]
There are 2 possible solution:

1. See if the a fake gcs server like: https://github.com/fsouza/fake-gcs-server could be used
2. Migrate the Google Cloud Storage back end to use the xml api insted of the json api and use something like https://min.io/ to test it locally, this has a benefit that this solution would work with other object stores too, like: MinIO, Google, Amazon, Azure

**Comment by agoston** [comment]
This is implemented since.
