### ISSUE TITLE
Fix the Windows build

### ISSUE THREAD

**Issue by Nonius** [bolcom/libunftp#205]
At the core team nobody uses Windows as a development environment, so the Windows build is failing. Would be nice if somebody who uses Windows would fix the build for it.

**Comment by RoyJacobs** [comment]
I built the current `master` of libunftp on my Windows 10 (version 20H2) and that worked fine, including tests. So perhaps it's something in the CI pipeline not going as expected?

**Comment by hannesdejager** [comment]
Good to hear. Does it run?

**Comment by RoyJacobs** [comment]
I only compiled the lib. Is there a example binary I could try, or should I just build the unftp project as well?

**Comment by hannesdejager** [comment]
You could try running `basic.rs` in the examples directory.

**Comment by RoyJacobs** [comment]
That works fine, I could connect via Filezilla and happily browse my temp folder.

**Comment by robklg** [comment]
According to @dani-garcia in #414 Windows is working 👍
