### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by alu** [bolcom/libunftp#21]
Hi guys.

I thinks processing TCP of this library is complicated.
The reason is control connection and data connection interact in both directions by channel.
I redesigned the process in [here](https://github.com/alu/libunftp/blob/master/src/server/mod.rs) (in progress).

My idia will all comannds process in `process()` and `responde()`.  `Session::process_data()` and channels be unnecessarily.

How do you think that?

**Comment by hannesdejager** [comment]
Hi Alu

Thanks for taking the time to try and improve the code. Simplification is a good thing.

You approach may work and it seems simpler. A couple of comments:

- Currently your suggestion doesn't seem to compile?
- I like the seperated respond method en the elimination of the extra channels.
- The respond method is way to long, this will need to be split up. 

I'll look more into it once it compiles.

**Comment by alu** [comment]
@hannesdejager Hi, thank you for reply.

> Currently your suggestion doesn't seem to compile?

Did you clone my repository and compile? I can compile the repository in my environment.

```sh
$ rustc --version
rustc 1.37.0 (eae3437df 2019-08-13)
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```

> The respond method is way to long, this will need to be split up.

I think that is generally desirable.
However, current style be nice for code locality because `Command` so many.
Why don't you switch to my design at the first, and then split if you want?

**Comment by alu** [comment]
@hannesdejager 
All of commands had implemented.
There is other necessary thing?

**Comment by hannesdejager** [comment]
Hi @alu, sorry for the delayed reply. I've been on holiday. Inititally I didn't clone your repository but pulled your master into my repository. This failed compiling. However when I cloned your repository it worked and I was able run to basic smoke tests.

So, how about you create a pull request with your changes and then I can discuss it with the libunftp team on Friday (we work on libunftp every Friday). 

Sounds OK. Please create a pull request then we take it from there.

**Comment by alu** [comment]
@hannesdejager Hi. I created PR in #25. Please check it out ;D

**Comment by hannesdejager** [comment]
Cool!, we'll have a look and discuss on Friday. Thanks for contributing.

**Comment by hannesdejager** [comment]
Closing since we didn't get far with the PR and the code changed tremendously.
