### ISSUE TITLE
How to configure per user permissions?

### ISSUE THREAD

**Issue by OrangeTux** [bolcom/libunftp#239]
Hello,  thanks for libunftp! It seems a promising library that I might want to try out.

I'm wondering if it's possible to limit certain resources to specific users. Let's say user A is only allowed to upload files at a certain place, while user B is only allowed to download certain files.

I guess it's possible by using the file systems permissions in case of using the Filesystem storage. But can I also configure permissions using something like `Authenticator`?

**Comment by hannesdejager** [comment]
Hi @OrangeTux, sorry for the delayed reply, its summer holiday time here. 

It is possible by providing your own implementations of:
1. the [UserDetail](https://docs.rs/libunftp/0.11.2/libunftp/auth/trait.UserDetail.html) trait
2. the [StorageBackend](https://docs.rs/libunftp/0.11.2/libunftp/storage/trait.StorageBackend.html) trait and 
3. the [Authenticator](https://docs.rs/libunftp/0.11.2/libunftp/auth/trait.Authenticator.html) trait.

and create your server using the [new_with_authenticator](https://docs.rs/libunftp/0.11.2/libunftp/struct.Server.html#method.new_with_authenticator) method.

e.g. 

```rust
#[derive(Debug)]
pub struct Account {
    pub username: String,
    pub enabled: bool,
    pub storage_location: PathBuf,
    pub allowed_to_download: T,
}

impl UserDetail for Account {
    fn account_enabled(&self) -> bool {
        self.enabled
    }
}

impl std::fmt::Display for Account {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Account")
    }
}

```

Your implementation of `Authenticator` should then return a configured instance of `Account` (or your UserDetail implementation). This will then be passed for your to your `StorageBackend` implementation. See the [docs here](https://docs.rs/libunftp/0.11.2/libunftp/storage/index.html) for implementing your own `StorageBackend`.

Hope this helps you in the right direction, let us know if you need help.

**Comment by OrangeTux** [comment]
Thanks for the response.

> sorry for the delayed reply, its summer holiday time here.

No problem at all. I understand. I'm on holiday as well so I'll try this when I get back to work.

**Comment by hannesdejager** [comment]
Hi @OrangeTux, did you manage to get this working?

**Comment by OrangeTux** [comment]
Yep. This is what I came up with.

``` rust
  #[derive(Debug, PartialEq, Copy, Clone)]
  pub enum UserType {
      ReadOnly,
      WriteOnly,
  }
  
  impl UserDetail for UserType {
      fn account_enabled(&self) -> bool {
          true
      }
  }

  impl std::fmt::Display for UserType {
      fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
          write!(f, "{:?}", self,)
      }
  }
  
  #[derive(Debug)]
  pub struct Credentials {
      pub username: String,
      pub password: String,
      pub usertype: UserType,
  }
  
  #[derive(Debug)]
  pub struct LookupAuthenticator {
      credentials: Vec<Credentials>,
  }

  impl libunftp::auth::Authenticator<UserType> for LookupAuthenticator {
        async fn authenticate(
          &self,
          username: &str,
          password: &str,
      ) -> Result<UserType, Box<dyn std::error::Error + Send + Sync>> {
          self.credentials 
              .iter() 
              .by_ref() 
              .find_map(|credential| { 
                  if (credential.username == username && credential.password == password) {
                      return Some(credential.usertype);
                  }
                  return None;
              }) 
              .ok_or(Box::new(AppError::AuthenticationError(
                  "User Authentication Failed".to_string(),
              )))
      }
  }
```

**Comment by hannesdejager** [comment]
Great, thanks for sharing!

I'll close this issue then.
