### ISSUE TITLE
Put does not work when using lftp and TLS on data channel

### ISSUE THREAD

**Issue by hannesdejager** [bolcom/libunftp#285]
When doing a put (STOR) with lftp with these settings on:

```
cat ~/.lftprc
debug
set cache:enable no
set ftp:ssl-allow yes
set ftp:ssl-allow-anonymous yes
set ftp:ssl-force yes
set ftp:ssl-auth TLS
set ftp:ssl-protect-data yes
set ssl:verify-certificate no
set ftp:ssl-use-ccc no
set ssl:use-sni no
```

and specifically `set ftp:ssl-protect-data yes`, then there is an issue to upload the file.

**Expected result:**

File uploads normally and the MD5 hashes of the source and destination files matches.

**Actual result:**

At about 100% progress things go wrong. unFTP returns a `451 Local error`. lftp then tries again using REST and completes but the MD5 hashes of the source and destination files differ. The destination file is missing bytes at the end. About 228K in this example:

![image](https://user-images.githubusercontent.com/2511554/100433276-20020700-309b-11eb-8656-4b9b8207ca69.png)

lftp debug info:

```
lftp hannes@mcnas:/> put Hedgewars-1.0.0.dmg
---> PASV
<--- 227 Entering Passive Mode (192,168,178,186,231,61)
---- Connecting data socket to (192.168.178.186) port 59197
---- Data connection established
---> STOR Hedgewars-1.0.0.dmg
<--- 150 Ready to receive data
Certificate depth: 0; subject: /CN=dejagers.local/O=De Jagers/C=NL; issuer: /CN=dejagers.local/O=De Jagers/C=NL
WARNING: Certificate verification: self signed certificate (B6:EA:AA:92:6F:A5:C5:9F:55:AD:F4:B1:41:48:CE:A9:1D:B2:E3:B9)
initialized translation from UTF-8 to ASCII
initialized translation from ASCII to UTF-8
WARNING: Certificate verification: certificate subject name 'dejagers.local' does not match target host name 'mcnas' (B6:EA:AA:92:6F:A5:C5:9F:55:AD:F4:B1:41:48:CE:A9:1D:B2:E3:B9)
---- Closing data socket
<--- 451 Local error
---> SIZE Hedgewars-1.0.0.dmg
<--- 213 185151488
---> PASV
copy: put rolled back to 185151488, seeking get accordingly
<--- 227 Entering Passive Mode (192,168,178,186,247,248)
---- Connecting data socket to (192.168.178.186) port 63480
---- Data connection established
---> REST 185151488
<--- 350 Restarting at 185151488. Now send STORE or RETRIEVE.
---> STOR Hedgewars-1.0.0.dmg
<--- 150 Ready to receive data
Certificate depth: 0; subject: /CN=dejagers.local/O=De Jagers/C=NL; issuer: /CN=dejagers.local/O=De Jagers/C=NL
WARNING: Certificate verification: self signed certificate (B6:EA:AA:92:6F:A5:C5:9F:55:AD:F4:B1:41:48:CE:A9:1D:B2:E3:B9)
initialized translation from UTF-8 to ASCII
initialized translation from ASCII to UTF-8
WARNING: Certificate verification: certificate subject name 'dejagers.local' does not match target host name 'mcnas' (B6:EA:AA:92:6F:A5:C5:9F:55:AD:F4:B1:41:48:CE:A9:1D:B2:E3:B9)
---- Closing data socket
<--- 451 Local error
---> SIZE Hedgewars-1.0.0.dmg
<--- 213 18446744073524494336
copy: all data received, but get rolled back
185628158 bytes transferred in 8 seconds (22.72 MiB/s)
```

the unFTP logs gives this:

```
Nov 13 11:24:24 mcnas.dejagers.local unftp[959151]: Nov 13 11:24:24.659 INFO Client requested to store a file, path: /Hedgewars-1.0.0.dmg, username: hannes, module: storage
Nov 13 11:24:24 mcnas.dejagers.local unftp[959151]: Nov 13 11:24:24.719 INFO Processing control channel event InternalMsg(StorageError(Error { kind: LocalError, source: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) })), seq: 47, trace-id: 0x35962d6b64838ff4, lib: libunftp
Nov 13 11:24:24 mcnas.dejagers.local unftp[959151]: Nov 13 11:24:24.719 INFO Result of processing control channel event Ok(CodeAndMsg { code: LocalError, msg: "Local error" }), seq: 47, trace-id: 0x35962d6b64838ff4, lib: libunftp
```

Notice the **_"Connection reset by peer"_**

A wireshark capture reveals that the lftp side sends a TCP RST to the unFTP side:

![image](https://user-images.githubusercontent.com/2511554/99050002-cf1ce980-2597-11eb-845c-69c904ba080d.png)

when using FileZilla (which works fine) we also see a RST but this time libuftp sends it after receiving a `FIN,ACK` from FileZilla.

![image](https://user-images.githubusercontent.com/2511554/99819591-efc4e080-2b4f-11eb-9297-132862d4e33d.png)

This issue is likely related to #242

Bug in rustls?: 

- https://github.com/denoland/deno/issues/6197
- https://github.com/denoland/deno/issues/7528
- https://github.com/seanmonstar/reqwest/issues/1039
- https://github.com/ctz/rustls/issues/273

**Comment by robklg** [comment]
apparently:

```V lftp/gnutls     unftp/Rustls
V lftp/libssl     unftp/openssl
X lftp/libssl     unftp/Rustls
V lftp/libssl     unftp/openssl

**Comment by hannesdejager** [comment]
> apparently:
> 
> ```
> V lftp/gnutls     unftp/Rustls
> V lftp/libssl     unftp/openssl
> X lftp/libssl     unftp/Rustls
> V lftp/libssl     unftp/openssl
> ```

yes `libunftp` with `rustls/tokio-rustls` used with lftp compiled with libssl is problematic. When I use [native-tls](https://crates.io/crates/native-tls) and [tokio-native-tls](https://crates.io/crates/tokio-native-tls) it works fine.

**Comment by hannesdejager** [comment]
TLS client hello from lftp:

![image](https://user-images.githubusercontent.com/2511554/107761431-071cff80-6d34-11eb-9a20-84ea098a694d.png)

Server Hello from libunftp:

![image](https://user-images.githubusercontent.com/2511554/107761569-3f244280-6d34-11eb-8eec-d4b1309a1e3a.png)
