### ISSUE TITLE
Option to specify the path in the bucket to use as root

### ISSUE THREAD

**Issue by hannesdejager** [bolcom/libunftp#287]
Currently the GCS back-end will use a hard coded path namely `/` as the root of the FTP data. 

Make this configurable. Perhaps use the same setting used for the filesystem back-end.

**Comment by robklg** [comment]
Please call the env var `UNFTP_ROOT_DIR`

**Comment by robklg** [comment]
Also export this feature via https://github.com/bolcom/unFTP s existing environment variable `UNFTP_ROOT_DIR`
