### ISSUE TITLE
libunftp accepts successive PASS commands

### ISSUE THREAD

**Issue by robklg** [bolcom/libunftp#361]
This is not in accordance with [RFC 959]( https://datatracker.ietf.org/doc/html/rfc959#section-4):

>         PASSWORD (PASS)
>
>            The argument field is a Telnet string specifying the user's
>            password.  This command must be immediately preceded by the
>            user name command, and, for some sites, completes the user's
>            identification for access control.  Since password
>            information is quite sensitive, it is desirable in general
>            to "mask" it or suppress typeout.  It appears that the
>            server has no foolproof way to achieve this.  It is
>            therefore the responsibility of the user-FTP process to hide
>            the sensitive password information.

(_"This command must be immediately preceded by the user name command"_)

**Comment by hannesdejager** [comment]
Fix available in [v0.18.0](https://github.com/bolcom/libunftp/releases/tag/libunftp-0.18.0)
