### ISSUE TITLE
Cannot connect to libunftp-based server with Cyberduck

### ISSUE THREAD

**Issue by Absolucy** [bolcom/libunftp#380]
Hi! I can't do much on any libunftp-based server with Cyberduck for macOS.

Mostly it either results in a truncated reply or this:
```
Could not parse response code.
Server Reply: drwxr-xr-x            1            0            0            192 Aug 23 10:08 Music. Please contact your web hosting service provider for assistance.
```

Sometimes it'll instead give an `Interoperability failure: 500 Always in binary mode` instead.

This is reproducible with the [`unftp-sbe-fs` basic example](https://github.com/bolcom/libunftp/blob/master/crates/unftp-sbe-fs/examples/basic.rs).

**Comment by robklg** [comment]
Thanks a lot for your issue report! We'll look into this soon and get back to you.

**Comment by robklg** [comment]
Hi @Absolucy can you test PR https://github.com/bolcom/libunftp/pull/381 please?

**Comment by Absolucy** [comment]
Yes, it does seem to work @robklg

**Comment by robklg** [comment]
What are using libunftp for if I may ask? (We're always interested to hear about how it's being used in the wild)

**Comment by Absolucy** [comment]
A rewrite of [Xenon](https://chariz.com/buy/xenon).

**Comment by robklg** [comment]
Nice! Looking at your GitHub repos, your work is very impressive. Hope libunftp will serve you and your users well.

**Comment by hannesdejager** [comment]
Resolved in release https://github.com/bolcom/libunftp/releases/tag/libunftp-0.18.1
