### ISSUE TITLE
Add graceful shutdown

### ISSUE THREAD

**Issue by bahlo** [bolcom/libunftp#386]
Would be great to get graceful shutdown. Right now I'm `tokio::select!`ing on the future of `libunftp::Server.listen` and my shutdown future, a.k.a just dropping the everything which isn't great.

**Comment by hannesdejager** [comment]
@bahlo I'm adding a `Server::shutdown_indicator` method:

![image](https://user-images.githubusercontent.com/2511554/141473840-d7f651a8-f539-4845-bde1-38a77825e6f7.png)

Usage will look something like this:

```
    let mut server = Server::with_authenticator(storage_backend, Arc::new(authenticator))
        .greeting("Welcome to unFTP")
        .passive_ports(start_port..end_port)
        .idle_session_timeout(idle_timeout)
        .logger(root_log.new(o!("lib" => "libunftp")))
        .passive_host(passive_host)
        .sitemd5(md5_setting)
        .shutdown_indicator(options::Shutdown::GracefulBlockingConnections( async move {
            shutdown.recv().await.ok();
            info!(l, "Shutting down FTP server");
        }))
        .metrics();
```

Let me know if you have more input.

**Comment by hannesdejager** [comment]
By the way feel free to share your use case for libunftp. It's always interesting for us :-).

**Comment by bahlo** [comment]
That looks great, can't wait! 

My use case: I have a printer with a scanner on top and I want to use that to scan documents (paperless and all that), but I 1. don't want to upload them to Dropbox or whatever the printer supports unencrypted and 2. don't want to send them via email. 

So I use libunftp to expose an FTP server in my local network that, when a file is uploaded will run OCR, store it locally and send a link via email that only resolves locally. That way I can save the document directly to my encrypted storage.

**Comment by hannesdejager** [comment]
Very nice!

**Comment by hannesdejager** [comment]
Available in version [0.18.2](https://github.com/bolcom/libunftp/releases/tag/libunftp-0.18.2)

**Comment by hannesdejager** [comment]
Ready for consumption @bahlo :-)

**Comment by bahlo** [comment]
Thanks, appreciate it! ❤️
