### ISSUE TITLE
start and stop by different methods

### ISSUE THREAD

**Issue by leo-je** [bolcom/libunftp#472]
I want to encapsulate two methods, start() and stop(), to control the startup and shutdown of the FTP service, but it seems that I can only start it. How can I implement stop()?

**Comment by hannesdejager** [comment]
Hi @leo-je , to strop you can provide a Future to the [`shutdown_indicator`](https://docs.rs/libunftp/0.18.9/libunftp/struct.Server.html#method.shutdown_indicator) method on Server

**Comment by hannesdejager** [comment]
@leo-je , hopefully you resolved it by now. I'm closing this.
