### ISSUE TITLE
Sometimes parameters seem to be not recognized as filenames

### ISSUE THREAD

**Issue by mdirkse** [bolcom/libunftp#61]
When giving a nonexistent filename like `t`, `f`, unftp does not display the filename in the error. It looks like some such characters are treated as if they are not a filename within libunftp. E.g.:

```
lftp localhost:/> rm t
rm: Access failed: 550 File not found
lftp localhost:/> rm u
rm: Access failed: 550 File not found
lftp localhost:/> rm d
rm: Access failed: 550 File not found
lftp localhost:/> rm e
rm: Access failed: 550 File not found
lftp localhost:/> rm f
rm: Access failed: 550 File not found
```

Some other characters don't have the issue:

```
lftp localhost:/> rm s
rm: Access failed: 550 File not found (s)
lftp localhost:/> rm v
rm: Access failed: 550 File not found (v)
lftp localhost:/> rm w
rm: Access failed: 550 File not found (w)
```

Although this looks like a benign bug, it could be more than that.

**Comment by robklg** [comment]
Turns out this is just a quirk/bug in lftp client. Libunftp does not send the path along with the error itself.
