### ISSUE TITLE
Migrate to std::future::Future and async/await

### ISSUE THREAD

**Issue by basdebue** [bolcom/libunftp#70]
In anticipation of async/await coming to stable Rust on November 7th, libraries like Tokio and Hyper have been preparing support for `std::future::Future` and eventually plan on dropping futures 0.1 entirely. It would be cool if `libunftp` came prepared for these major improvements in ergonomics too!

**Comment by hannesdejager** [comment]
Good issue this one. I sure hope we can pull this off.

**Comment by hannesdejager** [comment]
FYI, we're working towards this in branch: https://github.com/bolcom/libunftp/tree/shared/tokio-compat

**Comment by hannesdejager** [comment]
This is now done.

**Comment by hannesdejager** [comment]
Version 0.7.0 published to [crates.io](https://crates.io/crates/libunftp)

**Comment by hannesdejager** [comment]
[UnFTP server on master](https://github.com/bolcom/unFTP) using libunftp with this changes.
